spring: 
    application:
        name: ScandaPay
    datasource:
        url: 
            jdbc:postgresql://localhost:5432/scandaPay
        username: Holar
        password: Favour844@
        driver-class-name: org.postgresql.Driver
    jpa: 
        hibernate: 
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                "[format_sql]": true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQL16Dialect
    jwt_secret_key: c8c939284e5d48a18eb93e7f67008c031ada01d5f25bf70a04071e0d7134914a

    mail:
        host: smtp.gmail.com
        port: 587
        username: olasojifavour2021@gmail.com
        password: eauyvdlnhnwxsmcc

        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
        
server:
    port: 8000
